export const builderCatalogue = {
  meats: [
    {id:"beef80",label:"80/20 beef",kcal100:254,protein100:17.2,fat100:20,carbs100:0,yield:0.72,fatRetention:0.78,
      scores:{juiciness:94,tenderness:88,beefiness:96,richness:90,crust:91,structure:79},
      flavour:"Deep, familiar beef flavour with a rich finish.",texture:"Loose and succulent when handled gently.",bestUse:"Classic cheeseburgers, smash burgers and forgiving first cooks.",mistake:"Overworking it turns the naturally tender grind dense.",cooking:"Use high heat for thin patties; moderate the heat after searing thick patties.",health:"High flavour and moisture, but more calorie-dense because of its fat content."},
    {id:"beef85",label:"85/15 beef",kcal100:215,protein100:19,fat100:15,carbs100:0,yield:0.75,fatRetention:0.82,
      scores:{juiciness:84,tenderness:84,beefiness:94,richness:80,crust:92,structure:85},
      flavour:"Beef-forward with a cleaner, less fatty finish.",texture:"Tender but slightly firmer than 80/20.",bestUse:"Balanced everyday burgers and meal prep.",mistake:"Cooking it like 80/20 can push it past its moist window.",cooking:"Sear firmly, then stop cooking as soon as the centre reaches the target temperature.",health:"A useful balance of protein density, calories and eating quality."},
    {id:"beef90",label:"90/10 lean beef",kcal100:176,protein100:20.5,fat100:10,carbs100:0,yield:0.79,fatRetention:0.86,
      scores:{juiciness:70,tenderness:75,beefiness:91,richness:66,crust:94,structure:90},
      flavour:"Clean, pronounced beef flavour without much richness.",texture:"Firm and potentially dry if compressed or overcooked.",bestUse:"High-protein burgers and calorie-conscious builds.",mistake:"Adding more cooking time to create colour dries the centre.",cooking:"Use a hot pan, exterior seasoning and precise doneness; pair with a moisture-rich sauce.",health:"Highest protein per calorie among the beef options."},
    {id:"beefpork",label:"80% beef · 20% pork",kcal100:236,protein100:17.5,fat100:18,carbs100:0,yield:0.73,fatRetention:0.80,
      scores:{juiciness:92,tenderness:93,beefiness:80,richness:91,crust:87,structure:81},
      flavour:"Beef-led with gentle pork sweetness.",texture:"Soft, tender and slightly springier.",bestUse:"Thick patties, freezer meal prep and seasoned blends.",mistake:"Too much mixing creates a sausage-like bite.",cooking:"Cook fully and use slightly gentler heat after browning.",health:"Moist and satisfying, though not as protein-dense as lean beef."},
    {id:"beeflamb",label:"80% beef · 20% lamb",kcal100:248,protein100:17.8,fat100:19,carbs100:0,yield:0.73,fatRetention:0.80,
      scores:{juiciness:91,tenderness:87,beefiness:76,richness:95,crust:88,structure:82},
      flavour:"Deep, aromatic and earthy with a savoury finish.",texture:"Juicy and moderately firm.",bestUse:"Herb-forward burgers, sharp cheese and acidic condiments.",mistake:"Heavy sweet sauces can bury the lamb character.",cooking:"Use confident browning and pair with fresh acidity.",health:"Rich in flavour, but similar in calorie density to 80/20 beef."}
  ],
  cheeses: [
    {id:"none",label:"No cheese",grams:0,kcal:0,protein:0,fat:0,carbs:0,sodium:0,richness:0,structure:0,flavour:"Lets the patty and condiments lead.",texture:"No melted binding layer.",bestUse:"Lean, condiment-led or lower-calorie builds.",mistake:"Removing cheese without adding acidity or moisture can make a lean burger feel austere.",cooking:"Not applicable.",health:"Eliminates the cheese calories and sodium."},
    {id:"american",label:"American-style",grams:20,kcal:62,protein:3.2,fat:5,carbs:1.5,sodium:270,richness:9,structure:8,flavour:"Mild, salty and creamy.",texture:"The smoothest, most complete melt.",bestUse:"Smash burgers and classic cheeseburgers.",mistake:"Using multiple slices can dominate a small patty with salt.",cooking:"Add near the end and cover briefly.",health:"Moderate calories, but comparatively high sodium."},
    {id:"cheddar",label:"Cheddar",grams:22,kcal:89,protein:5.5,fat:7.3,carbs:0.3,sodium:137,richness:12,structure:5,flavour:"Sharp and tangy, stronger with age.",texture:"Rich melt that may split when very mature.",bestUse:"Beef-heavy and steakhouse burgers.",mistake:"Very aged cheddar may oil out rather than drape.",cooking:"Use thin slices and gentle covered heat.",health:"More protein than American-style cheese, with more calories."},
    {id:"swiss",label:"Swiss",grams:22,kcal:84,protein:6,fat:6.4,carbs:0.4,sodium:42,richness:9,structure:6,flavour:"Nutty, mild and savoury.",texture:"Supple melt with some stretch.",bestUse:"Mushroom, onion and lean beef burgers.",mistake:"A thick slice can stay rubbery in the centre.",cooking:"Slice thinly and cover the pan.",health:"Good protein with comparatively low sodium."},
    {id:"provolone",label:"Provolone",grams:22,kcal:77,protein:5.7,fat:5.8,carbs:0.5,sodium:193,richness:8,structure:7,flavour:"Mild, savoury and slightly tangy.",texture:"Reliable, cohesive melt.",bestUse:"Beef-pork blends and peppers.",mistake:"Its mild flavour disappears under very sweet sauces.",cooking:"Add for the final minute under a cover.",health:"Moderate calories and useful protein."},
    {id:"lightcheddar",label:"Reduced-fat cheddar",grams:22,kcal:62,protein:7,fat:3.5,carbs:0.6,sodium:170,richness:5,structure:5,flavour:"Cheddar-like tang with less richness.",texture:"Firmer melt than full-fat cheddar.",bestUse:"High-protein and lower-calorie builds.",mistake:"Overheating makes it tough rather than fluid.",cooking:"Use low residual heat and a cover.",health:"Highest cheese protein per calorie in this Builder."}
  ],
  buns: [
    {id:"brioche",label:"Brioche bun",kcal:220,protein:7,fat:7,carbs:33,sodium:340,structure:7,flavour:"Buttery and gently sweet.",texture:"Soft and rich.",bestUse:"Steakhouse and indulgent burgers.",mistake:"Too much sauce overwhelms its delicate crumb.",cooking:"Toast the cut face until golden.",health:"The most calorie-dense bun option."},
    {id:"potato",label:"Potato bun",kcal:170,protein:6,fat:3,carbs:31,sodium:280,structure:9,flavour:"Mild with subtle sweetness.",texture:"Soft, resilient and compressible.",bestUse:"Classic and smash burgers.",mistake:"Skipping the toast reduces moisture resistance.",cooking:"Toast lightly so it stays flexible.",health:"Lower calorie than brioche with excellent structure."},
    {id:"sesame",label:"Sesame bun",kcal:190,protein:6.5,fat:4,carbs:34,sodium:300,structure:8,flavour:"Neutral wheat flavour with toasted sesame.",texture:"Slightly firmer than potato bread.",bestUse:"Classic diner builds.",mistake:"A dry, oversized bun dilutes the patty.",cooking:"Toast the interior only.",health:"Middle-of-the-range calories and protein."},
    {id:"thin",label:"Thin wholemeal bun",kcal:120,protein:6,fat:2,carbs:22,sodium:230,structure:7,flavour:"Nutty and less sweet.",texture:"Light but moderately firm.",bestUse:"High-protein and calorie-conscious builds.",mistake:"Over-toasting makes it brittle.",cooking:"Use a brief light toast.",health:"Strong protein-to-calorie ratio for a bun."},
    {id:"lettuce",label:"Lettuce wrap",kcal:15,protein:1,fat:0.2,carbs:3,sodium:20,structure:4,flavour:"Fresh and neutral.",texture:"Crisp but less stable.",bestUse:"Very low-calorie and lower-carb builds.",mistake:"Wet leaves make the burger slippery.",cooking:"Dry thoroughly; no cooking needed.",health:"Lowest calories, but less filling than bread for some users."}
  ],
  sauces: [
    {id:"classic",label:"Classic burger sauce",kcal:92,protein:0.4,fat:9,carbs:3,sodium:190,moisture:9,flavour:"Creamy, tangy and gently sweet.",texture:"Rich emulsion.",bestUse:"Classic beef and smash burgers.",mistake:"A thick layer makes the stack slide.",cooking:"Spread thinly on a toasted bun.",health:"High flavour impact but calorie-dense."},
    {id:"mayo",label:"Mayonnaise",kcal:100,protein:0.1,fat:11,carbs:0.2,sodium:90,moisture:10,flavour:"Neutral richness.",texture:"Very creamy.",bestUse:"Lean patties that need lubrication.",mistake:"Using it with a high-fat patty can make the burger feel greasy.",cooking:"Apply after cooking.",health:"Highest-calorie sauce option."},
    {id:"mustard",label:"Yellow mustard",kcal:9,protein:0.5,fat:0.5,carbs:0.8,sodium:180,moisture:3,flavour:"Sharp, acidic and salty.",texture:"Thin and light.",bestUse:"Rich patties, onions and pickles.",mistake:"Too much can dominate subtle blends.",cooking:"Apply to the bun or sear onto a smash patty.",health:"Very low calories, though sodium remains relevant."},
    {id:"ketchup",label:"Ketchup",kcal:20,protein:0.2,fat:0,carbs:5,sodium:160,moisture:4,flavour:"Sweet, tangy tomato.",texture:"Smooth and moderately thick.",bestUse:"Classic family-friendly burgers.",mistake:"It can make sweet buns feel cloying.",cooking:"Apply in a controlled thin layer.",health:"Low calorie per serving, but contributes sugar and sodium."},
    {id:"yoghurt",label:"Greek-yoghurt sauce",kcal:28,protein:3,fat:0.8,carbs:2.1,sodium:75,moisture:8,flavour:"Tangy, fresh and lightly creamy.",texture:"Creamy but lighter than mayonnaise.",bestUse:"Lean beef, lamb and high-protein builds.",mistake:"Heating it directly can make it split.",cooking:"Apply after the patty leaves the heat.",health:"Adds protein and moisture for relatively few calories."},
    {id:"none",label:"No sauce",kcal:0,protein:0,fat:0,carbs:0,sodium:0,moisture:0,flavour:"No additional flavour layer.",texture:"Drier overall bite.",bestUse:"Very juicy patties or condiment-light testing.",mistake:"Lean patties can feel dry without another moisture source.",cooking:"Not applicable.",health:"Eliminates sauce calories."}
  ],
  onions: [
    {id:"none",label:"No onion in the mix",kcal:0,protein:0,fat:0,carbs:0,juiciness:0,beefiness:0,richness:0,crust:0,structure:0,tenderness:0,
      flavour:"The patty stays purely meat-forward.",texture:"Uniform, unbroken grind.",bestUse:"Showcasing a premium blend or dry-aged beef.",mistake:"Lean patties without onion lose an easy source of moisture and sweetness.",cooking:"Not applicable.",health:"No added calories.",
      insight:"Removing onion keeps the flavour purely beefy but gives up its quiet moisture and sweetness.",technique:"Nothing changes at the pan — cook exactly as the blend demands."},
    {id:"grated5",label:"Grated onion · 5 g per patty",kcal:2,protein:0.1,fat:0,carbs:0.5,juiciness:3,beefiness:-1,richness:1,crust:-1,structure:-1,tenderness:2,
      flavour:"A quiet background sweetness and savoury depth — most people taste better beef, not onion.",texture:"Slightly looser, juicier crumb.",bestUse:"Lean blends (90/10) and any patty that tends to dry out.",mistake:"Chopped instead of grated leaves crunchy pockets that break the patty apart.",cooking:"Squeeze out excess juice lightly, fold in with no more than five or six strokes.",health:"Negligible calories; adds moisture without fat.",
      insight:"5 g of grated onion melts invisibly into the mix — subtle sweetness, noticeably juicier bite, still beef-first.",technique:"Fold it in last with five or six gentle strokes; extra moisture means give the sear ten extra seconds before flipping."},
    {id:"grated10",label:"Grated onion · 10 g per patty",kcal:4,protein:0.2,fat:0,carbs:1,juiciness:5,beefiness:-3,richness:2,crust:-2,structure:-2,tenderness:3,
      flavour:"Clearly sweeter and more aromatic — the onion becomes a taste you can name.",texture:"Noticeably softer, wetter mix.",bestUse:"Robust blends like beef-lamb that can carry the sweetness.",mistake:"At this level, skipping the squeeze leaves the mix too wet to shape cleanly.",cooking:"Squeeze the grated onion firmly in a paper towel before folding in.",health:"Still trivial calories; the trade-off is structural, not nutritional.",
      insight:"10 g pushes onion from invisible helper to audible voice — sweeter, juicier, slightly less beef-pure.",technique:"Squeeze the pulp firmly first, chill the mix 10 minutes before shaping, and expect a slightly softer patty at the flip."}
  ],
  garlics: [
    {id:"none",label:"No garlic",kcal:0,protein:0,fat:0,carbs:0,juiciness:0,beefiness:0,richness:0,crust:0,structure:0,tenderness:0,
      flavour:"Clean canvas — the meat and seasoning speak alone.",texture:"No change.",bestUse:"Classic cheeseburgers where pure beef is the point.",mistake:"None — garlic is optional, not obligatory.",cooking:"Not applicable.",health:"No added calories.",
      insight:"No garlic keeps the profile classic and lets the beef fat carry the aroma.",technique:"No adjustment needed at the pan."},
    {id:"fresh",label:"Fresh garlic · 3 g minced",kcal:4,protein:0.2,fat:0,carbs:1,juiciness:0,beefiness:-1,richness:2,crust:0,structure:0,tenderness:0,
      flavour:"Sharp, hot and assertive — raw garlic bite that mellows only partially inside a quick-cooked patty.",texture:"Tiny firm flecks unless minced very finely.",bestUse:"Thick patties with longer cook times that tame the rawness.",mistake:"In a 90-second smash patty the garlic stays nearly raw and harsh.",cooking:"Mince to a paste; suits patties over 15 mm that cook long enough to sweeten it.",health:"Negligible calories.",
      insight:"Fresh garlic is the boldest choice — a hot, pungent edge that only partly mellows during the cook.",technique:"Only pair with thicker patties (15 mm+); a fast smash cook leaves it raw and aggressive."},
    {id:"powder",label:"Garlic powder · 0.5 g",kcal:2,protein:0.1,fat:0,carbs:0.4,juiciness:0,beefiness:1,richness:1,crust:0,structure:0,tenderness:0,
      flavour:"Even, toasty, savoury warmth through every bite — no hot spots, no bite.",texture:"Completely invisible in the crumb.",bestUse:"Smash patties and any thin, fast-cooked burger.",mistake:"Doubling the dose turns warmth into a dusty, acrid note.",cooking:"Blend it with the salt and pepper and season the outside, or fold through the mix evenly.",health:"Effectively zero calories.",
      insight:"Powder gives you garlic's warmth without its bite — evenly distributed, smash-safe and foolproof.",technique:"Works at any thickness and any cook speed; mix it with your salt so it spreads evenly."},
    {id:"roasted",label:"Roasted garlic · 8 g mashed",kcal:10,protein:0.3,fat:0.1,carbs:2.2,juiciness:2,beefiness:-1,richness:4,crust:-1,structure:-1,tenderness:1,
      flavour:"Sweet, nutty and mellow — closer to caramel than to raw garlic's heat.",texture:"Soft paste that enriches the crumb.",bestUse:"Steakhouse-style and lamb-blend burgers that welcome sweetness.",mistake:"Expecting garlic punch — roasting trades all the bite for sweetness.",cooking:"Mash cooled roasted cloves through the mix; the extra sugars brown faster, so watch the sear.",health:"Ten calories per patty — the richest garlic option, still minor.",
      insight:"Roasted garlic adds a sweet, nutty undertone that deepens richness — no sharpness at all.",technique:"Its sugars darken the crust sooner: sear thirty seconds less per side than usual."}
  ],
  seasonings: [
    {id:"classic",label:"Salt & black pepper",kcal:0,protein:0,fat:0,carbs:0,juiciness:0,beefiness:2,richness:0,crust:1,structure:0,tenderness:0,
      flavour:"The reference profile — salt amplifies the beef, pepper adds quiet heat at the finish.",texture:"Clean crust with visible pepper speck.",bestUse:"Every burger; the baseline you should master first.",mistake:"Salting the mix instead of the surface draws out protein and tightens the bite.",cooking:"Season the outside generously just before the pan.",health:"Sodium on the surface, where your tongue meets it first — efficient seasoning.",
      insight:"Salt and pepper is not a lack of choice — it is the profile that lets the meat itself be the flavour.",technique:"Season the surface just before searing, never the mix — surface salt builds crust, mixed salt builds bounce."},
    {id:"smoky",label:"Salt, pepper & smoked paprika",kcal:1,protein:0,fat:0,carbs:0.2,juiciness:0,beefiness:0,richness:2,crust:2,structure:0,tenderness:0,
      flavour:"A warm, barbecue-leaning smokiness under the beef — reads as 'grilled' even from a pan.",texture:"Deeper mahogany crust colour.",bestUse:"Beef-pork blends and indoor cooks chasing outdoor flavour.",mistake:"Hot paprika instead of smoked changes the profile from smoke to heat.",cooking:"Paprika scorches easily — keep the pan just below smoking and turn promptly.",health:"Effectively no calories.",
      insight:"Smoked paprika layers a gentle campfire note over the beef and deepens the crust colour.",technique:"Paprika burns before beef does — run the pan slightly cooler and flip on schedule."},
    {id:"herb",label:"Salt, pepper & dried herbs",kcal:1,protein:0,fat:0,carbs:0.2,juiciness:0,beefiness:-2,richness:1,crust:0,structure:0,tenderness:0,
      flavour:"Savoury and aromatic — oregano and thyme steer the patty toward Mediterranean territory.",texture:"Faint herb speck through the crumb.",bestUse:"Lamb blends, feta-adjacent toppings, yoghurt sauce builds.",mistake:"Fresh soft herbs (basil, parsley) blacken and turn bitter in the pan — use dried here.",cooking:"Rub dried herbs between your palms as you season to wake the oils.",health:"Effectively no calories.",
      insight:"Dried herbs pull the burger toward lamb-and-yoghurt territory — aromatic, savoury, less classic-diner.",technique:"Crush the herbs as you apply them and keep the sear standard; dried herbs tolerate the pan well."}
  ],
  toppings:{standard:{label:"Lettuce, tomato, onion & pickles",kcal:28,protein:1.2,fat:0.2,carbs:6.2,sodium:180,structure:5},minimal:{label:"Pickles & onion",kcal:12,protein:0.4,fat:0.1,carbs:2.7,sodium:170,structure:3}}
};
export const defaultBuild={name:"My Burger",meat:"beef85",weight:150,thickness:16,cheese:"american",bun:"potato",sauce:"classic",toppings:"standard",onion:"none",garlic:"none",seasoning:"classic"};
