import { assets } from "./assets.js";

const commonSteps = {
  mix: {image:assets.mixing,kicker:"STEP 1",title:"Keep the meat cold",body:"Combine only until the blend is even. Distinct strands and visible fat protect a tender bite."},
  shape: {image:assets.shaping,kicker:"STEP 2",title:"Shape with light pressure",body:"Form an even patty without kneading or compressing it into a dense puck."},
  dimple: {image:assets.dimple,kicker:"STEP 3",title:"Finish the shape",body:"For standard and thick patties, add a shallow centre indentation to reduce doming."},
  cook: {image:assets.finished,kicker:"STEP 4",title:"Cook for contrast",body:"Build a deep crust while protecting the interior. Adjust heat to the patty thickness rather than relying only on time."},
  cheese: {image:assets.cheese,kicker:"STEP 5",title:"Melt the cheese completely",body:"Add cheese near the end and cover briefly so it drapes around the patty without overcooking the centre."},
  assemble: {image:assets.layers,kicker:"STEP 6",title:"Assemble for balance",body:"Toast the bun, spread sauce evenly and keep every layer centred so the first and last bite taste consistent."}
};

export const recipes=[
 {id:"classic-cheeseburger",title:"Classic Cheeseburger",collection:"Classics",hero:assets.heroClassic,flavour:"Beef-forward, tangy and familiar",texture:"Juicy centre, crisp edge, soft bun",time:"25 min",difficulty:"Easy",macros:{calories:648,protein:39,fat:37,carbs:39},ingredients:["150 g 85/15 beef","1 potato bun","1 American-style cheese slice","Burger sauce","Pickles, onion, lettuce and tomato"],build:{name:"Classic Cheeseburger",meat:"beef85",weight:150,thickness:16,cheese:"american",bun:"potato",sauce:"classic",toppings:"standard"},steps:[commonSteps.mix,commonSteps.shape,commonSteps.dimple,commonSteps.cook,commonSteps.cheese,commonSteps.assemble]},
 {id:"classic-smash",title:"Classic Smash Burger",collection:"Classics",hero:assets.heroSmash,flavour:"Deeply browned, salty and savoury",texture:"Maximum crust with thin, tender patties",time:"18 min",difficulty:"Easy",macros:{calories:612,protein:36,fat:35,carbs:38},ingredients:["140 g 80/20 beef, divided","1 potato bun","1 American-style cheese slice","Yellow mustard","Pickles and onion"],build:{name:"Classic Smash Burger",meat:"beef80",weight:140,thickness:7,cheese:"american",bun:"potato",sauce:"mustard",toppings:"minimal"},steps:[commonSteps.mix,{image:assets.portion,kicker:"STEP 2",title:"Portion loose meat balls",body:"Divide the cold meat without pre-compressing it. Loose balls spread more easily and create irregular crisp edges."},{image:assets.thickness,kicker:"STEP 3",title:"Smash thin and wide",body:"Press firmly only during the first moments of cooking. A thin patty maximises contact with the hot surface."},commonSteps.cook,commonSteps.cheese,commonSteps.assemble]},
 {id:"high-protein",title:"High-Protein Classic",collection:"High Protein",hero:assets.heroHighProtein,flavour:"Clean beef flavour with bright acidity",texture:"Firm-tender and moist rather than greasy",time:"24 min",difficulty:"Easy",macros:{calories:492,protein:46,fat:18,carbs:31},ingredients:["170 g 90/10 beef","1 thin wholemeal bun","Reduced-fat cheddar","Greek-yoghurt burger sauce","Pickles, onion, lettuce and tomato"],build:{name:"High-Protein Classic",meat:"beef90",weight:170,thickness:16,cheese:"lightcheddar",bun:"thin",sauce:"yoghurt",toppings:"standard"},steps:[commonSteps.mix,commonSteps.shape,commonSteps.dimple,{image:assets.finished,kicker:"STEP 4",title:"Stop cooking earlier",body:"Lean beef has less margin for error. Sear confidently, then remove it as soon as the target doneness is reached."},commonSteps.cheese,commonSteps.assemble]},
 {id:"lower-calorie",title:"Lean Mustard Burger",collection:"Lower Calorie",hero:assets.heroCross,flavour:"Sharp, savoury and pickle-forward",texture:"Light, crisp and compact",time:"20 min",difficulty:"Easy",macros:{calories:356,protein:34,fat:13,carbs:24},ingredients:["140 g 90/10 beef","1 lettuce wrap or thin bun","Yellow mustard","Pickles and white onion","No cheese"],build:{name:"Lean Mustard Burger",meat:"beef90",weight:140,thickness:12,cheese:"none",bun:"lettuce",sauce:"mustard",toppings:"minimal"},steps:[commonSteps.mix,commonSteps.shape,{image:assets.thickness,kicker:"STEP 3",title:"Keep it moderately thin",body:"A thinner lean patty cooks quickly and develops more crust before the centre dries out."},commonSteps.cook,{image:assets.sauce,kicker:"STEP 5",title:"Use acidity instead of excess fat",body:"Mustard and pickles deliver strong flavour for relatively few calories and keep the burger lively."},commonSteps.assemble]},
 {id:"beef-pork",title:"Beef & Pork Provolone",collection:"Flavour Forward",hero:assets.heroEditorial,flavour:"Rich, subtly sweet and savoury",texture:"Exceptionally tender and juicy",time:"28 min",difficulty:"Medium",macros:{calories:702,protein:38,fat:43,carbs:39},ingredients:["160 g beef–pork blend","1 brioche bun","1 slice provolone","Dijon-style burger sauce","Pickles and onion"],build:{name:"Beef & Pork Provolone",meat:"beefpork",weight:160,thickness:18,cheese:"provolone",bun:"brioche",sauce:"classic",toppings:"minimal"},steps:[commonSteps.mix,commonSteps.shape,commonSteps.dimple,{image:assets.finished,kicker:"STEP 4",title:"Cook the pork blend through",body:"Because the blend contains pork, cook it to a safe internal temperature while managing heat to preserve tenderness."},commonSteps.cheese,commonSteps.assemble]},
 {id:"beef-lamb",title:"Beef & Lamb Burger",collection:"Flavour Forward",hero:assets.heroClassic,flavour:"Earthy, aromatic and deeply savoury",texture:"Juicy with a substantial bite",time:"28 min",difficulty:"Medium",macros:{calories:676,protein:40,fat:40,carbs:36},ingredients:["160 g beef–lamb blend","1 sesame bun","Swiss or provolone","Greek-yoghurt sauce","Red onion, tomato and lettuce"],build:{name:"Beef & Lamb Burger",meat:"beeflamb",weight:160,thickness:18,cheese:"swiss",bun:"sesame",sauce:"yoghurt",toppings:"standard"},steps:[commonSteps.mix,commonSteps.shape,commonSteps.dimple,commonSteps.cook,commonSteps.cheese,commonSteps.assemble]}
];

export function recipeById(id){return recipes.find(recipe=>recipe.id===id);}
