import { assets, RAW } from "./assets.js";

export const recipes = [
  {
    id: "classic-cheeseburger",
    title: "Classic Cheeseburger",
    collection: "Classics",
    hero: assets.heroClassic,
    flavour: "Savoury, rich and balanced",
    texture: "Juicy centre with a lightly toasted bite",
    time: "20 min",
    difficulty: "Easy",
    macros: { calories: 654, protein: 35, fat: 38, carbs: 40 },
    ingredients: ["150 g 80/20 beef", "1 potato bun", "1 American-style cheese slice", "Burger sauce", "Pickles, onion, lettuce and tomato"],
    build: { name: "Classic Cheeseburger", meat: "beef85", weight: 150, thickness: 16, cheese: "american", bun: "potato", sauce: "classic", toppings: "standard" },
    steps: [
      { image: `${RAW}/heroes/ingredients/BM-HERO-ING-001-classic-cheeseburger-layout.webp`, kicker: "PREP", title: "The Classic Layout", body: "Gather your ingredients. The classic cheeseburger relies on the balance of rich beef, sharp American cheese, and fresh, crisp vegetables. It is the benchmark against which all other burgers are measured." },
      { image: `${RAW}/ingredients/beef/BM-ING-BEEF-001-80-20-ground-chuck.webp`, kicker: "MEAT", title: "Select 80/20 Chuck", body: "Use freshly ground 80/20 beef chuck. The 20% fat content is crucial — it bastes the meat from the inside out, ensuring a juicy medium-rare to medium centre." },
      { image: assets.portion, kicker: "PORTION", title: "Weigh to 150 grams", body: "Portion exactly 150 grams of cold meat on a scale. This weight provides a substantial bite without overwhelming the bun. Eyeballing leads to uneven cooking." },
      { image: assets.mixing, kicker: "TECHNIQUE", title: "Handle gently", body: "Keep the meat cold. Do not knead it like dough. The more you compress the mince, the denser and more sausage-like the final patty will be." },
      { image: assets.shaping, kicker: "SHAPE", title: "Shape the patty", body: "Form a loose, even patty slightly wider than your bun — it will shrink as it cooks. Use just enough pressure to hold it together." },
      { image: assets.dimple, kicker: "DIMPLE", title: "Add a thumb dimple", body: "Press a shallow indentation into the centre. As the proteins contract under heat, the edges pull in. The dimple prevents the patty from doming like a meatball." },
      { image: assets.seasoningSalt, kicker: "SEASON", title: "Weigh the salt", body: "Aim for about 1.5 grams of salt for this 150 g patty — roughly 1% of its weight. Do not mix the salt into the meat; season the outside only, from a height of 25–30 cm for even coverage, right before the patty hits the pan." },
      { image: `${RAW}/cooking/BM-COOK-001-first-contact.webp`, kicker: "SEAR", title: "First contact", body: "Place the seasoned side down into a smoking hot cast-iron pan. You should hear an aggressive sizzle immediately. If it is quiet, your pan is too cold." },
      { image: assets.seasoningOneSide, kicker: "SEASON", title: "Season the top", body: "While the bottom sears, season the raw top side. We wait until now because salt draws out moisture — seasoning too early creates a wet surface that steams instead of searing." },
      { image: `${RAW}/cooking/BM-COOK-004-ideal-flip-timing.webp`, kicker: "PATIENCE", title: "Wait for the crust", body: "Leave the burger alone. Moving it too early prevents a proper crust. Wait until a deep brown crust forms and the meat releases naturally from the pan — about 3 minutes." },
      { image: `${RAW}/cooking/BM-COOK-007-finished-crust.webp`, kicker: "FLIP", title: "The Maillard reaction", body: "Flip to reveal a perfect, nutty-brown crust. This crust is where the deepest savoury flavours live. Cook the second side for about 2 minutes." },
      { image: `${RAW}/cross-sections/BM-XSEC-001-rare-cross-section.webp`, kicker: "TIMING", title: "Why times are only a guide", body: "Exact timing depends on patty weight, thickness, meat blend, fat percentage, the meat's starting temperature, your cooking surface, and heat level. For a 150 g patty at ¾ inch (1.9 cm) from the fridge on hot cast iron, expect roughly 2–4 minutes per side." },
      { image: `${RAW}/cross-sections/BM-XSEC-003-medium-cross-section.webp`, kicker: "THERMOMETER", title: "Trust the thermometer", body: "Colour lies — pans, lighting, and blends all skew it. A probe thermometer does not: 54°C is medium-rare, 60°C is medium, 71°C is well done. Check the centre and take the guesswork out entirely." },
      { image: `${RAW}/cheese/BM-CHEESE-001-american-before-melt.webp`, kicker: "CHEESE", title: "Apply American cheese", body: "Place one slice of American cheese on the patty during the final minute of cooking. American cheese is chosen here for its unmatched melting qualities." },
      { image: `${RAW}/cheese/BM-CHEESE-002-perfect-american-melt.webp`, kicker: "MELT", title: "Cover and melt", body: "Cover the pan briefly. The cheese is melting from trapped steam beneath the cover, draping it perfectly over the edges without overcooking the centre." },
      { image: `${RAW}/cross-sections/BM-XSEC-010-resting-juices.webp`, kicker: "REST", title: "Rest the patty", body: "Move the patty to a warm plate for two minutes. Resting allows juices to redistribute before the first bite — cut too early and they end up on the plate instead of in the burger." },
      { image: `${RAW}/assembly/BM-ASM-001-toasted-brioche-bottom-bun.webp`, kicker: "BUILD", title: "Toast the bun", body: "While the patty rests, toast the potato bun in butter until golden brown. This creates a barrier against juices and adds a roasted flavour." },
      { image: `${RAW}/assembly/BM-ASM-010-correct-burger-sauce-spread.webp`, kicker: "BUILD", title: "Apply burger sauce", body: "Spread an even layer of classic burger sauce on both the top and bottom buns. Go all the way to the edges." },
      { image: `${RAW}/assembly/BM-ASM-020-correct-pickle-placement.webp`, kicker: "BUILD", title: "Layer the vegetables", body: "Stack pickles, raw onion rings, lettuce, and a slice of tomato on the bottom bun. Putting wet ingredients on the bottom anchors the burger." },
      { image: `${RAW}/assembly/BM-ASM-025-patty-onto-vegetables.webp`, kicker: "BUILD", title: "Place the patty", body: "Transfer the hot, cheesy patty directly onto the vegetable stack. The heat will slightly soften the raw onions." },
      { image: `${RAW}/assembly/BM-ASM-033-correct-top-bun-placement.webp`, kicker: "BUILD", title: "Crown the burger", body: "Place the sauced top bun on the patty and press down very gently to unify the layers." },
      { image: `${RAW}/cross-sections/BM-XSEC-003-medium-cross-section.webp`, kicker: "FINISH", title: "Perfect medium centre", body: "The result is a beautifully layered burger with a juicy, pink medium centre and a crisp exterior. The contrast between the hot, rich beef and the cool, crisp vegetables is the hallmark of a classic." },
      { image: `${RAW}/cross-sections/BM-XSEC-009-dry-interior-macro.webp`, kicker: "TROUBLESHOOT", title: "If it came out dry", body: "A dry burger means it went past temperature — usually from trusting the clock instead of the thermometer, or from a patty thinner than planned. Next time, pull it 2–3°C early; the centre keeps cooking as it rests." },
      { image: assets.heroBeefPairing, kicker: "VARIATIONS", title: "Make it your own", body: "Once you own the classic, vary one element at a time: swap in sharp cheddar for extra bite, caramelised onions for sweetness, or a brioche bun for richness. Changing one variable per cook is how you learn what each actually does." }
    ]
  },
  {
    id: "classic-smash",
    title: "Classic Smash Burger",
    collection: "Classics",
    hero: assets.heroSmash,
    flavour: "Deeply browned, salty and savoury",
    texture: "Maximum crust with thin, tender patties",
    time: "18 min",
    difficulty: "Easy",
    macros: { calories: 612, protein: 36, fat: 35, carbs: 38 },
    ingredients: ["140 g 80/20 beef, divided", "1 potato bun", "1 American-style cheese slice", "Yellow mustard", "Pickles and onion"],
    build: { name: "Classic Smash Burger", meat: "beef80", weight: 140, thickness: 7, cheese: "american", bun: "potato", sauce: "mustard", toppings: "minimal" },
    steps: [
      { image: `${RAW}/heroes/ingredients/BM-HERO-ING-005-smash-burger-layout.webp`, kicker: "PREP", title: "The Smash Layout", body: "A smash burger is all about the meat and the crust. Keep toppings minimal: sharp mustard, dill pickles, and finely diced onions. The beef is the star." },
      { image: `${RAW}/ingredients/beef/BM-ING-BEEF-001-80-20-ground-chuck.webp`, kicker: "MEAT", title: "Select 80/20 Chuck", body: "You must use 80/20 beef. Leaner blends will stick to the pan and dry out completely when smashed thin, because there isn't enough fat to lubricate the crust." },
      { image: assets.portion, kicker: "PORTION", title: "Divide into two", body: "Divide 140 grams of cold meat into two 70-gram portions. Weigh them — uneven patties will finish cooking at different times." },
      { image: `${RAW}/meat/BM-MEAT-005-correct-gentle-mixing.webp`, kicker: "SHAPE", title: "Roll loosely", body: "Roll the portions into loose balls. Do not pack them tightly; a loose structure helps the fat render out and fry the edges when smashed." },
      { image: assets.onionDice, kicker: "PREP", title: "Dice the onions", body: "Finely dice white onions (about 3 mm pieces). Dicing spreads the onion's punch evenly across every bite and allows them to soften quickly on the hot meat." },
      { image: `${RAW}/cooking/BM-COOK-002-fifteen-seconds-sear.webp`, kicker: "SMASH", title: "Smash thin and wide", body: "Place the balls in a screaming hot dry pan. Immediately smash them completely flat using a heavy spatula and a rolling pin for leverage. Do not wait." },
      { image: `${RAW}/cooking/BM-COOK-003-first-crust-forming.webp`, kicker: "SEAR", title: "Hold the pressure", body: "Hold the pressure down hard for 10 seconds. This locks the meat to the steel, ensuring maximum crust formation and preventing the patty from shrinking back." },
      { image: assets.seasoningEven, kicker: "SEASON", title: "Season the raw side", body: "Season the exposed raw side heavily with salt and pepper. Because the patty is so thin, this one side of seasoning is enough for the entire piece of meat." },
      { image: `${RAW}/cooking/BM-COOK-008-macro-crust-texture.webp`, kicker: "TIMING", title: "Read the patty, not the clock", body: "On a properly hot surface a smashed patty needs only 60–90 seconds on the first side — but that window shifts with your pan's heat retention, the patty's exact thickness, and how cold the meat went in. Watch for pooling juices on top; that is your cue." },
      { image: `${RAW}/cooking/BM-COOK-008-macro-crust-texture.webp`, kicker: "SCRAPE", title: "Scrape, don't lift", body: "Use a sharp spatula to aggressively scrape under the patty. You must keep the dark, lacy crust attached to the meat, not the pan. A timid lift leaves the best part of the burger behind." },
      { image: `${RAW}/cheese/BM-CHEESE-011-american-slices.webp`, kicker: "CHEESE", title: "Apply American cheese", body: "Flip the patties. The cooked side should be entirely covered in a dark brown crust. Immediately place a slice of American cheese on one patty." },
      { image: `${RAW}/assembly/BM-ASM-027-centered-burger-stack.webp`, kicker: "STACK", title: "Stack the patties", body: "Place the second patty on top of the cheese to create a double stack. The intense residual heat from the two thin patties will melt the cheese instantly." },
      { image: `${RAW}/assembly/BM-ASM-002-toasted-potato-bottom-bun.webp`, kicker: "BUILD", title: "Toast a potato bun", body: "A soft, squishy potato bun is the perfect vessel for a smash burger. Toast it lightly to give it just enough structure to hold the greasy patties." },
      { image: `${RAW}/assembly/BM-ASM-011-correct-mustard-spread.webp`, kicker: "BUILD", title: "Apply yellow mustard", body: "Spread sharp yellow mustard on the bottom bun. The acidity is necessary to cut through the intensely rich, fatty crust of the smashed beef." },
      { image: `${RAW}/assembly/BM-ASM-020-correct-pickle-placement.webp`, kicker: "BUILD", title: "Add pickles and onion", body: "Layer dill pickles and the finely diced white onions. This sharp, crunchy foundation balances the heavy Maillard flavours." },
      { image: `${RAW}/assembly/BM-ASM-034-slight-press-after-assembly.webp`, kicker: "BUILD", title: "Crown and press", body: "Place the double patty stack on the bun, crown it, and give it a slight press to marry the layers together." },
      { image: `${RAW}/heroes/BM-HERO-004-macro-crust-edge.webp`, kicker: "FINISH", title: "Lacy, crispy edges", body: "The perfect smash burger is defined by its overhanging, crispy, lacy edges and intensely beefy flavour. Serve and eat immediately while the crust is hot — smash burgers do not wait." },
      { image: `${RAW}/cooking/BM-COOK-011-cold-pan-mistake.webp`, kicker: "TROUBLESHOOT", title: "If the patty turned grey", body: "A grey, steamed patty means the pan was not hot enough when you smashed. The surface must be well past 200°C so the thin patty browns before it overcooks. Preheat longer than feels reasonable, and smash one patty at a time if your pan is small." },
      { image: assets.onionMidCaramel, kicker: "VARIATIONS", title: "The Oklahoma variation", body: "For a famous variation, press a handful of paper-thin onion slices into the raw ball before smashing. The onions steam and caramelise directly into the patty as it cooks — sweet, deeply savoury, and built into the crust itself." }
    ]
  },
  {
    id: "high-protein",
    title: "High-Protein Classic",
    collection: "High Protein",
    hero: assets.heroHighProtein,
    flavour: "Clean beef flavour with bright acidity",
    texture: "Firm-tender and moist rather than greasy",
    time: "24 min",
    difficulty: "Easy",
    macros: { calories: 492, protein: 46, fat: 18, carbs: 31 },
    ingredients: ["170 g 90/10 beef", "1 thin wholemeal bun", "Reduced-fat cheddar", "Greek-yoghurt burger sauce", "Pickles, onion, lettuce and tomato"],
    build: { name: "High-Protein Classic", meat: "beef90", weight: 170, thickness: 16, cheese: "lightcheddar", bun: "thin", sauce: "yoghurt", toppings: "standard" },
    steps: [
      { image: `${RAW}/heroes/ingredients/BM-HERO-ING-002-high-protein-layout.webp`, kicker: "PREP", title: "The High-Protein Layout", body: "This build swaps fat for protein. We use a larger, leaner patty, reduced-fat cheddar, and a yoghurt-based sauce to hit 46 g of protein for under 500 calories." },
      { image: `${RAW}/ingredients/beef/BM-ING-BEEF-003-90-10-lean-beef.webp`, kicker: "MEAT", title: "Select 90/10 Beef", body: "Use 90/10 lean beef. It provides significantly more protein per calorie than 80/20, but because it lacks fat, it requires careful cooking to prevent drying out." },
      { image: assets.portion, kicker: "PORTION", title: "A larger 170g patty", body: "Because the meat is lean, we can increase the portion size to 170 grams to maximize the protein payload without blowing the calorie budget. Weigh it precisely." },
      { image: assets.shaping, kicker: "SHAPE", title: "Shape with care", body: "Lean beef binds tightly. Shape the patty gently and do not overwork it, or it will become tough. Add a thumb dimple to the centre." },
      { image: assets.seasoningEven, kicker: "SEASON", title: "Season heavily", body: "Lean beef needs flavour help. Season the outside heavily with salt and pepper. Do not mix salt into the meat, which would further toughen the lean proteins." },
      { image: `${RAW}/cooking/BM-COOK-005-freshly-flipped.webp`, kicker: "SEAR", title: "Sear quickly", body: "Sear over high heat. Lean beef has less margin for error, so we want to build a crust rapidly without giving the centre time to overcook." },
      { image: `${RAW}/cooking/BM-COOK-004-ideal-flip-timing.webp`, kicker: "TIMING", title: "Timing is a range", body: "For a 170 g lean patty at ¾ inch (1.9 cm) from the fridge, expect roughly 2–3 minutes per side on high heat — but weight, thickness, fat percentage, starting temperature, surface, and heat level all move that window. Watch the meat, not the clock." },
      { image: `${RAW}/cooking/BM-COOK-010-perfect-patty-no-cheese.webp`, kicker: "THERMOMETER", title: "Stop cooking earlier", body: "Remove the patty as soon as a thermometer reads 57–60°C at the centre — medium-rare to medium. Lean beef becomes tough, dry, and crumbly if cooked to well-done, and colour alone will not warn you in time." },
      { image: `${RAW}/cross-sections/BM-XSEC-010-resting-juices.webp`, kicker: "REST", title: "Rest — especially lean meat", body: "Rest the patty for two minutes. With so little fat, every drop of juice matters; resting lets the muscle fibres relax and reabsorb moisture instead of dumping it on the cutting board." },
      { image: `${RAW}/cheese/BM-CHEESE-012-sharp-cheddar-slices.webp`, kicker: "CHEESE", title: "Reduced-fat cheddar", body: "Apply a slice of sharp, reduced-fat cheddar. It melts reasonably well under a cover and provides strong flavour for fewer calories than standard cheese." },
      { image: `${RAW}/ingredients/buns/BM-BUN-006-english-muffin.webp`, kicker: "BUILD", title: "Use a thin bun", body: "Use a thin wholemeal bun or English muffin to reduce empty carbohydrates while maintaining the structural integrity of a burger." },
      { image: `${RAW}/condiments/BM-COND-008-greek-yoghurt-burger-sauce.webp`, kicker: "BUILD", title: "Yoghurt-based sauce", body: "Spread a sauce made from Greek yoghurt, ketchup, and relish. It mimics classic burger sauce but adds protein and moisture instead of heavy fat." },
      { image: `${RAW}/assembly/BM-ASM-018-correct-tomato-placement.webp`, kicker: "BUILD", title: "Add fresh moisture", body: "Layer plenty of lettuce and thick tomato slices. These add essential moisture to compensate for the leaner beef." },
      { image: assets.onionSlices, kicker: "BUILD", title: "Add raw onions", body: "Add raw onion slices. The sharp bite provides the excitement that is normally delivered by rendered beef fat." },
      { image: `${RAW}/assembly/BM-ASM-021-complete-vegetable-stack.webp`, kicker: "BUILD", title: "Assemble the stack", body: "Place the heavy 170 g patty on the vegetables, crown the burger, and serve immediately while the lean meat is still hot and juicy." },
      { image: `${RAW}/cross-sections/BM-XSEC-002-medium-rare-cross-section.webp`, kicker: "FINISH", title: "Dense and satisfying", body: "A massive 46 g of protein in a satisfying, substantial burger that fits perfectly into a macro-conscious diet without tasting like a compromise." },
      { image: `${RAW}/cross-sections/BM-XSEC-009-dry-interior-macro.webp`, kicker: "TROUBLESHOOT", title: "If it came out dry", body: "Dryness in a lean patty means it overshot 60°C. Next time pull it at 57°C — carry-over cooking adds 2–3 degrees during the rest — and lean harder on the yoghurt sauce and tomato for moisture insurance." },
      { image: assets.heroChickenPairing, kicker: "VARIATIONS", title: "The chicken swap", body: "For an even leaner profile, swap in 170 g of ground chicken thigh. Season it more aggressively than beef, cook it fully to 74°C, and let chipotle mayo and pepper jack supply the richness the meat gives up." }
    ]
  },
  {
    id: "lower-calorie",
    title: "Lean Mustard Burger",
    collection: "Lower Calorie",
    hero: `${RAW}/heroes/BM-HERO-ASM-006-lower-calorie-burger-hero.webp`,
    flavour: "Sharp, savoury and pickle-forward",
    texture: "Light, crisp and compact",
    time: "20 min",
    difficulty: "Easy",
    macros: { calories: 356, protein: 34, fat: 13, carbs: 24 },
    ingredients: ["140 g 95/5 beef", "1 lettuce wrap or thin bun", "Yellow mustard", "Pickles and white onion", "No cheese"],
    build: { name: "Lean Mustard Burger", meat: "beef95", weight: 140, thickness: 12, cheese: "none", bun: "lettuce", sauce: "mustard", toppings: "minimal" },
    steps: [
      { image: `${RAW}/heroes/ingredients/BM-HERO-ING-003-low-calorie-layout.webp`, kicker: "PREP", title: "The Low-Calorie Layout", body: "To cut calories drastically without losing the burger experience, we eliminate cheese, use extra-lean beef, and rely on mustard and pickles for flavour." },
      { image: `${RAW}/ingredients/beef/BM-ING-BEEF-004-95-5-extra-lean-beef.webp`, kicker: "MEAT", title: "Select 95/5 Beef", body: "Use 95/5 extra-lean beef. It has almost no fat, saving hundreds of calories, but it requires specific techniques to remain edible." },
      { image: `${RAW}/meat/BM-MEAT-008-ready-to-shape.webp`, kicker: "PORTION", title: "Keep it moderate", body: "Portion 140 grams of meat. A massive patty of extra-lean beef becomes tiring to chew, so a moderate size is best. Weigh it carefully." },
      { image: assets.onionGrated, kicker: "MOISTURE TRICK", title: "Grate onion into the mix", body: "Here is the lean-meat secret: grate 15 g of raw onion on a fine grater, squeeze out the excess juice, and fold it gently through the mince. The onion pulp seasons the patty from within and adds back the moisture the missing fat took away." },
      { image: assets.mixing, kicker: "MIX", title: "Fold, never knead", body: "Combine with open fingers and stop the moment the onion disappears into the meat. Extra-lean beef turns tough faster than any other mince when overworked — it has no fat to buffer the compression." },
      { image: `${RAW}/patty/BM-PATTY-005-no-dimple-comparison.webp`, kicker: "SHAPE", title: "Keep it moderately thin", body: "Shape the patty thinner than usual — about ½ inch (1.2 cm). A thinner lean patty cooks quickly and develops crust before the centre dries out." },
      { image: assets.seasoningEven, kicker: "SEASON", title: "Heavy seasoning", body: "Without fat to carry flavour, the seasoning must do the heavy lifting. Salt and pepper the outside aggressively just before cooking." },
      { image: `${RAW}/cooking/BM-COOK-006-second-side-crust.webp`, kicker: "SEAR", title: "Fast and hot", body: "Sear over very high heat — roughly 2 minutes per side for this thickness, though your pan, heat level, and the meat's starting temperature will shift that. You want to establish a crust and get it out of the pan immediately." },
      { image: `${RAW}/cross-sections/BM-XSEC-009-dry-interior-macro.webp`, kicker: "THERMOMETER", title: "Beware the dry centre", body: "Extra-lean beef has no fat to lubricate the muscle fibres. Check with a thermometer and pull it at 57–60°C — past medium, it becomes unpleasantly dry and crumbly, and no topping can rescue it." },
      { image: `${RAW}/cross-sections/BM-XSEC-010-resting-juices.webp`, kicker: "REST", title: "A short rest", body: "Give the patty ninety seconds on a warm plate. Resting allows the scarce juices to redistribute before the first bite instead of flooding out at the first cut." },
      { image: `${RAW}/ingredients/buns/BM-BUN-007-lettuce-wrap.webp`, kicker: "BUILD", title: "Use a lettuce wrap", body: "To save 150+ calories, swap the bun for a crisp iceberg lettuce wrap, or use a very thin, low-calorie bun alternative." },
      { image: `${RAW}/condiments/BM-COND-003-yellow-mustard.webp`, kicker: "BUILD", title: "Use acidity, not fat", body: "Skip the mayonnaise. Yellow mustard delivers strong, sharp flavour for fewer than 10 calories and keeps the burger lively." },
      { image: `${RAW}/ingredients/vegetables/BM-VEG-006-pickles.webp`, kicker: "BUILD", title: "Heavy on the pickles", body: "Layer dill pickles and white onion generously. Their crunch and acidity replace the satisfaction normally provided by cheese and fat." },
      { image: `${RAW}/assembly/BM-ASM-023-clean-layering-macro.webp`, kicker: "BUILD", title: "Assemble the burger", body: "Wrap the hot patty tightly in the lettuce or place it on your thin bun." },
      { image: `${RAW}/cross-sections/BM-XSEC-008-juicy-interior-macro.webp`, kicker: "FINISH", title: "Light and sharp", body: "At under 360 calories, this burger provides a sharp, savoury hit without the heavy, lethargic aftermath of a classic build." },
      { image: `${RAW}/patty/BM-PATTY-003-overcompressed-mistake.webp`, kicker: "TROUBLESHOOT", title: "If it fell apart or bounced", body: "Crumbling means the patty was too dry — more grated onion and an earlier pull next time. A rubbery, bouncy bite means it was overworked or salted through the mix. Lean beef punishes both mistakes; gentleness fixes both." },
      { image: assets.seasoningPaprika, kicker: "VARIATIONS", title: "Build flavour without calories", body: "Smoked paprika in the outside seasoning, a swipe of Dijon instead of yellow mustard, or pickled jalapeños in the stack all add loud flavour for almost zero calories. Lean cooking is seasoning-forward cooking." }
    ]
  },
  {
    id: "beef-pork",
    title: "Beef & Pork Provolone",
    collection: "Flavour Forward",
    hero: `${RAW}/heroes/BM-HERO-ASM-008-editorial-beauty-shot.webp`,
    flavour: "Rich, subtly sweet and savoury",
    texture: "Exceptionally tender and juicy",
    time: "28 min",
    difficulty: "Medium",
    macros: { calories: 702, protein: 38, fat: 43, carbs: 39 },
    ingredients: ["160 g beef–pork blend", "1 brioche bun", "1 slice provolone", "Dijon-style burger sauce", "Pickles and onion"],
    build: { name: "Beef & Pork Provolone", meat: "beefpork", weight: 160, thickness: 18, cheese: "provolone", bun: "brioche", sauce: "classic", toppings: "minimal" },
    steps: [
      { image: assets.heroBeefPorkPairing, kicker: "PREP", title: "The Pork Blend Pairing", body: "Blending pork into beef creates an incredibly tender, slightly sweet patty. Everything around it is chosen to match: mild provolone, sweet brioche, sharp Dijon, and caramelised onions that echo the pork's natural sugars." },
      { image: `${RAW}/heroes/ingredients/BM-HERO-ING-007-beef-vs-beef-pork-comparison.webp`, kicker: "COMPARE", title: "Why blend at all?", body: "Side by side, pure beef reads bolder but pork-blended mince cooks up noticeably juicier and more tender. The blend borrows pork's soft fat and sweetness while beef keeps the burger tasting like a burger." },
      { image: `${RAW}/meat/BM-MEAT-002-pork-hero.webp`, kicker: "MEAT", title: "Blend 70/30", body: "Mix 70% ground beef with 30% ground pork. The pork fat renders easily, ensuring a juicy burger even when cooked all the way through." },
      { image: assets.portion, kicker: "PORTION", title: "Weigh to 160 grams", body: "Portion 160 grams of the cold blend. The extra 10 grams accounts for the pork fat that will render out during cooking." },
      { image: `${RAW}/patty/BM-PATTY-003-overcompressed-mistake.webp`, kicker: "WARNING", title: "Do not over-compress", body: "Pork blends can become sausage-like if overworked. Shape the 160 g patty with very light hands, just enough to hold it together." },
      { image: `${RAW}/patty/BM-PATTY-007-macro-edge-detail.webp`, kicker: "SHAPE", title: "A thick, rustic edge", body: "Leave the edges slightly rough. This allows the rendered pork fat to crisp up beautifully in the pan, creating crunchy edges." },
      { image: assets.dimple, kicker: "DIMPLE", title: "Add the dimple", body: "Press a dimple into the centre. This thick ¾ inch (1.9 cm) patty will dome significantly without it." },
      { image: assets.seasoningEven, kicker: "SEASON", title: "Season heavily", body: "Season the outside generously with salt and pepper. The sweet pork fat needs plenty of salt to bring out its savoury qualities." },
      { image: `${RAW}/cooking/BM-COOK-011-cold-pan-mistake.webp`, kicker: "WARNING", title: "Ensure the pan is hot", body: "Do not put the patty into a cold pan. Pork fat renders quickly; if the pan isn't screaming hot, the patty will boil in its own juices instead of searing." },
      { image: `${RAW}/cooking/BM-COOK-019-uneven-cooking-mistake.webp`, kicker: "THERMOMETER", title: "Cook it through — verified", body: "Because the blend contains pork, it must reach a safe 71°C at the centre — confirm it with a thermometer, never by colour. For this thick patty expect roughly 4–5 minutes per side on medium-high, but let the probe make the final call." },
      { image: assets.onionSweating, kicker: "MEANWHILE", title: "Start the onions early", body: "While the patty cooks, sweat sliced onions in a second pan over low heat until translucent — about 5–8 minutes with no browning. This is the first stage of the caramelised onions this burger deserves." },
      { image: assets.onionFullCaramel, kicker: "ONIONS", title: "Take them to mahogany", body: "Keep the heat low and let time do the work — 30–40 minutes to a glossy, jammy sweetness. If you are short on time, sweated onions from the previous step still beat raw here; sweetness is what pork wants." },
      { image: `${RAW}/cheese/BM-CHEESE-014-provolone.webp`, kicker: "CHEESE", title: "Apply Provolone", body: "Use a slice of mild provolone. Its smooth, slightly smoky flavour complements the sweet pork without overpowering it like a sharp cheddar would." },
      { image: `${RAW}/cheese/BM-CHEESE-005-provolone-melt.webp`, kicker: "MELT", title: "A perfect, stretchy melt", body: "Cover and melt the provolone until it drapes heavily over the edges of the thick patty." },
      { image: `${RAW}/condiments/BM-COND-004-dijon-mustard.webp`, kicker: "BUILD", title: "Dijon burger sauce", body: "Spread a sauce made with a heavy hit of Dijon mustard onto a toasted brioche bun. The mustard spice cuts the rich pork fat perfectly." },
      { image: `${RAW}/assembly/BM-ASM-009-correct-mayonnaise-spread.webp`, kicker: "BUILD", title: "Even coverage", body: "Ensure the sauce reaches all the way to the edges of the bun, so every bite is lubricated." },
      { image: `${RAW}/assembly/BM-ASM-019-correct-onion-placement.webp`, kicker: "BUILD", title: "Onions and pickles", body: "Spoon the caramelised onions over the melted provolone and add pickles below the patty. The onions read as a sweet sauce; the pickles supply the acid that keeps the richness in check." },
      { image: `${RAW}/assembly/BM-ASM-029-double-patty-alignment.webp`, kicker: "BUILD", title: "Stack the burger", body: "Place the heavy patty on the vegetables and crown with the top bun." },
      { image: `${RAW}/cross-sections/BM-XSEC-004-medium-well-cross-section.webp`, kicker: "FINISH", title: "Tender and safe", body: "A medium-well centre that remains incredibly juicy thanks to the pork fat, delivering a rich, complex flavour profile." },
      { image: `${RAW}/cooking/BM-COOK-011-cold-pan-mistake.webp`, kicker: "TROUBLESHOOT", title: "If it stewed instead of seared", body: "A pale, wet patty means the pan lost too much heat when the meat went in. Pork fat releases liquid early; a heavy pan preheated hard shrugs that off, a thin cold one drowns in it. Preheat longer and resist crowding the pan." },
      { image: `${RAW}/cheese/BM-CHEESE-004-swiss-melt.webp`, kicker: "VARIATIONS", title: "Swap the accent", body: "Swiss instead of provolone leans nuttier; BBQ sauce instead of Dijon leans smokier and sweeter. Keep the 70/30 blend constant and change one accent at a time — that is how you find your house version." }
    ]
  },
  {
    id: "beef-lamb",
    title: "Beef & Lamb Burger",
    collection: "Flavour Forward",
    hero: `${RAW}/heroes/BM-HERO-ASM-009-burger-held-one-hand.webp`,
    flavour: "Earthy, aromatic and deeply savoury",
    texture: "Juicy with a substantial bite",
    time: "28 min",
    difficulty: "Medium",
    macros: { calories: 676, protein: 40, fat: 40, carbs: 36 },
    ingredients: ["160 g beef–lamb blend", "1 sesame bun", "Swiss or provolone", "Greek-yoghurt sauce", "Red onion, tomato and lettuce"],
    build: { name: "Beef & Lamb Burger", meat: "beeflamb", weight: 160, thickness: 18, cheese: "swiss", bun: "sesame", sauce: "yoghurt", toppings: "standard" },
    steps: [
      { image: assets.heroBeefLambPairing, kicker: "PREP", title: "The Lamb Blend Pairing", body: "Lamb brings an earthy, robust flavour that demands cooling, fresh company: Swiss cheese, garlic-yoghurt sauce, mint, and sharp red onion. This board is Mediterranean on purpose — those cuisines solved lamb long ago." },
      { image: `${RAW}/heroes/ingredients/BM-HERO-ING-008-beef-vs-beef-lamb-comparison.webp`, kicker: "COMPARE", title: "Why blend with beef?", body: "Pure lamb can overwhelm a first-timer. The 50/50 blend grounds the burger in beef's familiar umami while the lamb's aromatics ride on top — bold enough to be interesting, familiar enough to be loved." },
      { image: `${RAW}/meat/BM-MEAT-003-lamb-hero.webp`, kicker: "MEAT", title: "Blend 50/50", body: "Mix equal parts ground beef and ground lamb. This grounds the burger in familiar umami while letting the lamb's aromatic qualities shine." },
      { image: `${RAW}/meat/BM-MEAT-006-overmixed-meat-mistake.webp`, kicker: "WARNING", title: "Do not overmix", body: "Lamb fat is dense. If you overmix the blend, the patty will become incredibly tough and heavy on the palate. Mix gently with open fingers." },
      { image: assets.portion, kicker: "PORTION", title: "Weigh to 160 grams", body: "Portion 160 grams of the cold blend. This size ensures the bold lamb flavour is the undeniable centrepiece of the burger." },
      { image: `${RAW}/patty/BM-PATTY-008-ready-for-cooking.webp`, kicker: "SHAPE", title: "A thick 160g patty", body: "Shape a thick, ¾ inch (1.9 cm) patty. Lamb benefits from a robust sear and a juicy, medium-rare centre, which requires thickness." },
      { image: assets.dimple, kicker: "DIMPLE", title: "Add the dimple", body: "Press a dimple into the centre. Thick patties dome heavily as the proteins contract, and a domed burger is hard to stack." },
      { image: assets.seasoningEven, kicker: "SEASON", title: "Season aggressively", body: "Lamb can take aggressive seasoning. Salt and pepper the outside heavily. The bold meat needs bold seasoning to match it." },
      { image: `${RAW}/cooking/BM-COOK-012-smoking-hot-pan-mistake.webp`, kicker: "WARNING", title: "Manage the smoke", body: "Lamb fat smokes heavily when it hits a hot pan. Ensure your extractor fan is on high and your windows are open before searing." },
      { image: `${RAW}/cooking/BM-COOK-009-crosslight-crust-detail.webp`, kicker: "SEAR", title: "Build a heavy crust", body: "Sear aggressively. The robust flavour of lamb can stand up to a very dark, heavily charred crust without tasting burnt." },
      { image: `${RAW}/cross-sections/BM-XSEC-002-medium-rare-cross-section.webp`, kicker: "THERMOMETER", title: "Aim for medium-rare to medium", body: "This blend is at its best between 57 and 60°C at the centre — juicy, rosy, and aromatic. For a ¾ inch (1.9 cm) patty expect roughly 3–4 minutes per side, but thickness, starting temperature, and your pan all shift that. Verify with the probe." },
      { image: `${RAW}/cheese/BM-CHEESE-013-swiss-cheese.webp`, kicker: "CHEESE", title: "Apply Swiss cheese", body: "Use a slice of Swiss cheese. Its nutty, mellow flavour pairs beautifully with earthy lamb without fighting it for attention." },
      { image: `${RAW}/cheese/BM-CHEESE-004-swiss-melt.webp`, kicker: "MELT", title: "A glossy melt", body: "Melt the Swiss until glossy under a cover. It will not drape as heavily as American cheese, but it provides excellent texture." },
      { image: `${RAW}/ingredients/buns/BM-BUN-003-sesame-bun.webp`, kicker: "BUILD", title: "Toast a sesame bun", body: "The nutty, roasted flavour of sesame seeds is the perfect match for lamb. Toast it in butter until golden." },
      { image: assets.garlicMinced, kicker: "SAUCE PREP", title: "Mince the garlic for the sauce", body: "Finely mince one fresh clove. It goes into the yoghurt, never into the meat — raw garlic in the patty scorches and turns bitter in the pan, but in the cool sauce it stays bright and pungent." },
      { image: `${RAW}/condiments/BM-COND-001-mayonnaise.webp`, kicker: "BUILD", title: "Garlic yoghurt sauce", body: "Stir the minced garlic into Greek yoghurt with lemon juice and a pinch of salt. The acidity and coolness cut through the dense lamb fat — this sauce is not optional on a lamb burger." },
      { image: `${RAW}/ingredients/vegetables/BM-VEG-004-red-onion.webp`, kicker: "BUILD", title: "Add red onions", body: "Use sharp, raw red onions instead of white. Their pungency stands up to the lamb's bold flavour much better." },
      { image: `${RAW}/assembly/BM-ASM-026-perfect-cheese-alignment.webp`, kicker: "BUILD", title: "Stack the burger", body: "Place the heavy, cheese-topped patty on the vegetables and crown it." },
      { image: `${RAW}/cross-sections/BM-XSEC-010-resting-juices.webp`, kicker: "REST", title: "Let it rest", body: "Allow the burger to rest for a minute before eating. Resting allows the dense lamb juices to redistribute through the patty instead of rushing out at the first bite." },
      { image: `${RAW}/meat/BM-MEAT-006-overmixed-meat-mistake.webp`, kicker: "TROUBLESHOOT", title: "If it tasted heavy or tough", body: "A leaden lamb burger almost always traces back to overmixing — dense lamb fat compacts fast. If the flavour felt overwhelming instead, shift the ratio to 70/30 beef-to-lamb next time and add more yoghurt sauce and mint." },
      { image: assets.heroLambPairing, kicker: "VARIATIONS", title: "Go full Mediterranean", body: "Crumble feta instead of Swiss, add fresh mint leaves to the stack, and dust the patty with smoked paprika before searing. Each step deepens the Mediterranean character this burger is already leaning toward." }
    ]
  }
];

export function recipeById(id) {
  return recipes.find(recipe => recipe.id === id);
}
